### ISSUE TITLE
Document's getBlob() does not return the data of the blob if content_type is specified

### ISSUE THREAD

**Issue by azaddhirajkumar** [Couchbase-Ecosystem/cbl-ionic#26]
The getBlob() method of the Document class does not return the blob's data even if the content_type is set.

<img width="401" alt="Screenshot 2024-06-13 at 8 19 26 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/130559389/437c5a80-b237-47a8-a5fb-f8254d265cb1">

**Comment by khanium** [comment]
Team, we are hitting this issue. Is there any workaround?

**Comment by biozal** [comment]
This is fixed in 0.1.9 - @azaddhirajkumar can you please re-run your tests to validate.  I updated the Example app Get Document and Editor pages to inject in multiple blobs on a single document and then the Get Document page will get the content if it's a text blob.  Get should now properly return hello world for the text content on any document from the Editor page if you select a generated document that has a blob type.

**Comment by biozal** [comment]
Fixed in 0.1.9
