### ISSUE TITLE
App crashes when calling replicator_GetPendingDocumentIds

### ISSUE THREAD

**Issue by brydecena** [Couchbase-Ecosystem/cbl-ionic#44]
**Describe the bug**
When you call replicator_GetPendingDocumentIds, the app crashes.
Please see error logs below on XCode:
<img width="1195" alt="Screenshot 2024-06-16 at 5 58 50 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/5e14f39c-684c-4f5e-9b39-d7e76741a04c">

The crash is coming from this line, it's unable to resolve the plugin call:
<img width="711" alt="Screenshot 2024-06-16 at 9 07 06 PM" src="https://github.com/Couchbase-Ecosystem/cbl-ionic/assets/166391797/3e95c7d4-c693-49fb-afbb-4a0ecdb7353c">

**Expected behavior**
The plugin should return the pending document id's if there are any and not cause the application to crash

**Current behavior**
App crashes and there is no return on the hybrid code.

**Plugin Version**
3.x

**Affected Platforms (please complete the following information):**
 - Device: [e.g. iPad]
 - OS: [e.g. iOS17.4]

**Comment by biozal** [comment]
I just tested again in the example app and we don't see an exception when calling the pendingIds method, so I'll need more information and the exact code that is being called with a full callstack to troubleshoot this further.

**Comment by biozal** [comment]
My guess this is because of Set<String> which is what ReplicatorManager is returning the data type as back.  0.2.0 will change this to an Array of String instead.  Not sure why your app is crashing, in the Example app we don't crash at all, the documentIds simply don't show up.  I tweaked the code in the e2e replicator test on my locale machine to validate that this doesn't crash:
https://github.com/Couchbase-Ecosystem/cblite-js/blob/main/cblite-tests/e2e/replicator-test.ts#L147C9-L147C40

I'll note we don't have a test for Pending Document Id's yet - I'll talk with @azaddhirajkumar about getting one added.  @azaddhirajkumar this is really hard to test, you have to add a crazy amount of documents before you can get this to fire since for me on my machine replication runs so fast.  I used App Services in Capella and then replicated the entire travel sample _default._default to test - 65,000 documents takes to long and eventually have to cancel out, so we we'll need a better data set to test this with than that.

**Comment by brydecena** [comment]
Hi @biozal , you are probably right the issue is because of the Set, since we are using cordova to wrap the native components, cordova probably does not handle that kind of return unlike in capacitor, because here the issue is in the return which is handled by cordova on our side.

For this issue, we just encountered it upon checking with the method 'replicator_GetPendingDocumentIds', but probably we won't be using it in the app that we are currently updating, we just filed the bug for reference.

Thanks!
